<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>..\lib\</BaseOutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="LNLibSharp">
      <HintPath>..\runtimes\win-64\native\LNLibSharp.dll</HintPath>
      <EmbedInteropTypes>False</EmbedInteropTypes>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="VL.Core" Version="2025.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Curve\NewFolder\" />
  </ItemGroup>
</Project>
